title: GlitchSecure
description: > # this means to ignore newlines until "show_excerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: https://glitchsecure.com # where is the production site located?
companyname: GlitchSecure

# Social media links
social:
  twitter: glitchsecure
  linkedin: glitchsecure
  github: glitchsecure

permalink: "/blog/:title/"

plugins:
  - jekyll-feed
  - jekyll-postcss
  - jekyll-sitemap
  - jekyll-minifier

postcss:
  cache: false

css_dir: "assets/css" # defaults to "css"

highlighter: rouge

collections:
  posts:
    output: true
    permalink: "/blog/:title"
  pages:
    output: true
    permalink: "/:title"

jekyll-minifier:
  exclude: "*.txt"
  exclude: "publickey.asc"
  exclude: "feed.xml"
  exclude: "security.md"
  uglifier_args:
    harmony: true


jekyll_image_optim:
  image_optim:
    allow_lossy: true
    advpng:
      level: 2
    optipng:
      level: 2
# Enable these if you want extra optimization:
    pngout: false
    svgo: false

webrick:
  headers:
    Access-Control-Allow-Origin: "*"


exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - postcss.config.js
  - README.md
  - tailwind.config.js
