title: GlitchSecure
description: "Automatically assess your security posture with continuous vulnerability assessments and real-time pentesting."
url: https://glitchsecure.com # where is the production site located?
companyname: GlitchSecure
lang: en-CA
logo: /assets/img/logo-square-whitebg.png
email: hello@glitchsecure.com
phone: "+1-647-370-1337"
address:
  street: 120 Sherbrook St
  locality: Winnipeg
  region: MB
  postal_code: R3C 2B4
  country: CA


# Social media links
social:
  twitter: glitchsecure
  linkedin: glitchsecure
  github: glitchsecure

plugins:
  - jekyll-feed
  - jekyll-postcss
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-paginate-v2

postcss:
  cache: false

css_dir: "assets/css" # defaults to "css"

highlighter: rouge

collections:
  posts:
    output: true
    permalink: "/:slugified_categories/:title"
  pages:
    output: true
    permalink: "/:title"


pagination:
  enabled: true
  per_page: 6
  sort_field: 'date'
  sort_reverse: true

autopages:
  enabled: true
  sort_field: 'date'
  sort_reverse: true
  tags:
    enabled: false
  collections:
    enabled: false
  categories:
    enabled: true
    layouts:
        - 'categories.html'
    permalink: '/:cat'
    title: 'The latest :cat from GlitchSecure'

show_drafts: false



jekyll-minifier:
  exclude:
    - "*.txt"
    - ".well-known/security.txt"
    - "publickey.asc"
    - "feed.xml"
    - "security.md"
    - "assets/js/bundle.js"
  compress_css: false
  uglifier_args:
    harmony: true


jekyll_image_optim:
  image_optim:
    allow_lossy: true
    advpng:
      level: 2
    optipng:
      level: 2
# Enable these if you want extra optimization:
    pngout: false
    svgo: false

webrick:
  headers:
    Access-Control-Allow-Origin: "*"


exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - postcss.config.js
  - README.md
  - tailwind.config.js
