backend:
  name: github
  repo: glitchsecure/website
  branch: main
  base_url: https://cms.glitchsecure.com
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Updated Date', name: 'date-updated', widget: 'datetime' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Collaborators', name: 'collaborators', widget: 'list' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - label: 'Image'
        name: 'image'
        widget: 'object'
        summary: '{{fields.credit}}'
        fields:
          - { label: 'Hero', name: 'hero', widget: 'image', choose_url: true }
          - { label: 'Feature', name: 'feature', widget: 'image', choose_url: 'true' }
          - { label: 'Credit Name', name: 'credit', widget: 'string' }
          - { label: 'Credit Link', name: 'creditlink', widget: 'string' }
      - { label: 'Hero Is Vertical', name: 'hero-vertical', widget: 'boolean' default: true}
      - { label: 'Hero Wrapper Padding Class', name: 'hero-wrapper-padding', widget: 'string', default: 'pb-24' }
      - { label: 'Enable Comments', name: 'comments', widget: 'boolean', default: true }
      - { label: 'Body', name: 'body', widget: 'markdown' }

