on:
   push:
     branches: [ main ]
   pull_request:
     branches: [ main ]

jobs:
   build:

     runs-on: ubuntu-latest

     steps:
      - name: GitHub Checkout
        uses: actions/checkout@v3
      - name: Bundler Cache
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Dependencies
        run: npm install

      - name: Run esbuild JS bundler
        run: npm run esbuild

      - name: Build & Deploy to GitHub Pages
        uses: glitchsecure/jekyll4-deploy-gh-pages@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
