on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v3
        # checkout the private repo containing the action to run
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v3
        with:
          repository: GlitchSecure/jekyll4-deploy-gh-pages
          ref: refs/heads/main
          token: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}
          path: .github/actions/jekyll4-deploy-gh-pages
      - name: Bundler Cache
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.0
          bundler-cache: true

      - name: Build & Deploy to GitHub Pages
        uses: ./.github/actions/jekyll4-deploy-gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_REPOSITORY_PUBLIC: "GlitchSecure/public-website"
          GITHUB_PUSH_TOKEN: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
